baseurl = "http://127.0.0.1"
title = "Suppe og analyse"
author = "Eivind"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Stol på suppe - alle andre må vise data"

[[menu.main]]
    name = "Hjem"
    url = "http://127.0.0.1:4321"
    weight = 1
[[menu.main]]
    name = "Om meg"
    url = "http://127.0.0.1:4321/om-meg/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/gardenberg"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/road2stat"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
